spring:
  application:
    name: team
  datasource:
    url: jdbc:mysql://localhost:3306/team
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    # user.name: "sandeep"
    # user.password: "root"
    jwt:
      secret-key: 271d05b82f97e8fa070f913c85544e2c9d9e8e5851bb3821976dbaf8510a3835
      expiration-time: 3600000 
server:
  port: 8080    
     